Video_Game/Areas/GamersArea/Controllers/GamersController.cs
using Microsoft.AspNetCore.Mvc;
using Video_Game.Areas.GamersArea.Models;
using Video_Game.Data;
using Video_Game.Models;

namespace Video_Game.Areas.GamersArea.Controllers
{
    [Area("GamersArea")]
    public class GamersController : Controller
    {
        private readonly CardDbContext _context;
        private readonly  IWebHostEnvironment _environment;
        private gamesmodel _gamesmodel;
        public GamersController(CardDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
            _gamesmodel = new gamesmodel(_context, _environment);
        }

        private Gamer FindUser()
        {
            var id = HttpContext.Session.GetInt32("userid");
            if (id != null)
            {
                return _context.Gamers.Find(id);
            }
            return null;
        }

        



        public IActionResult Home()
        {
            var newgame = _gamesmodel.newgame();

            ViewBag.User = FindUser();
            ViewBag.game = newgame;
            return View();
        }
        

        public IActionResult Game()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SershBy(string name)
        {
            var game = _gamesmodel.SerchBy(name);
            if (game != null)
            {
                ViewBag.game = game;
                return RedirectToAction("Game");
            }
            return View("Game");
        }




    }
}

Video_Game/Areas/GamersArea/Views/Shared/_LayoutGamer.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/gamer/css/gamer.css" rel="stylesheet" type="text/css"  />
    <link href="~/gamer/css/card.css" rel="stylesheet" type="text/css"  />
    @RenderSection("Styles", required: false)
    <title>@ViewBag.Title</title>
</head>
<body>
    <header>
        <h1>متجر ألعاب الفيديو</h1>
        <nav>
            <a asp-area="GamersArea" asp-controller="Gamers" asp-action="Home">الرئيسية</a>
            <a asp-area="GamersArea" asp-controller="Gamers" asp-action="Game">الألعاب</a>
            <a href="#">العروض</a>
            <a href="#">تواصل معنا</a>
        </nav>
    </header>

    @RenderBody()


    <footer>
        <p>جميع الحقوق محفوظة © 2024 متجر ألعاب الفيديو</p>
    </footer>
</body>
</html>

Video_Game/Areas/GamersArea/Views/Shared/_list.cshtml
@{
    var listgame = ViewBag.game;
}

    @foreach (var item in listgame)
    {
        <div class="game-card">
            <img src="@item.ImagePath" alt="لعبة 1">
            <h4>@item.Titel الاسم</h4>
            <p>@item.Price$ السعر</p>
        </div>
    }